services:
  - type: web
    name: kindle-reader
    env: docker
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
    buildCommand: |
      docker build -t kindle-reader .
    startCommand: |
      docker run -p $PORT:80 kindle-reader
    autoDeploy: true
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryUtilizationPercent: 70
      targetCPUUtilizationPercent: 70
